# Site wide configuration

title: "Microsoft UK PDU"
description: "This is a site for the UK Cloud Infra and Management Team"
logo: MSLogo.jpg
teaser: MSLogo.jpg
locale: en-GB
timezone: Europe/London
url: https://ukpdu.github.io
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
kramdown:
  input: GFM
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Front matter defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      comments: true
      share: true

# Site owner
owner:
  name: Adam Bohle
  email: adam.bohle@microsoft.com
  twitter: https://twitter.com/adambohle
  bio:
  avatar: abohle-bio.jpg # 160x160 px image for author byline
  disqus-shortname: https-ukpdu-github-io

include:
  - .htaccess
  - "_pdu"
  - "_workshops"
  - "_posts"
  - "_pages"
  - "_blogs"
  - "_landingpages"
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
