# Site wide configuration

title: "Microsoft UK PDU Cloud Infrastructure & Management Site"
description: "This is a site for the UK Cloud Infra and Management Team"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
timezone: Europe/London
url: https://ukpducim.github.io
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Adam Bohle
  email: adam.bohle@microsoft.com
  twitter: https://twitter.com/adambohle
  bio:
  avatar: abohle-bio.jpg # 160x160 px image for author byline
  disqus-shortname: https-ukpducim-github-io

include:
  - .htaccess
  - "_pdu"
  - "_workshops"
  - "_posts"
  - "_blogs"
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp